### PR TITLE
Revamp

### PR DESCRIPTION
**Pull request by gibbiemonster**
Add rainbow "4w55" and Robot Mono font.

### CODE REVIEW

**Comment by gibbiemonster** [comment]
@SpeeedyAtGithub Review pls

**Comment by gibbiemonster** [comment]
Pog

**Comment by SpeeedyAtGithub** [comment]
E

**Comment by SpeeedyAtGithub** [comment]
What now

**Comment by gibbiemonster** [comment]
re-open it

**Pull request merged**
